### PR TITLE
default color for preview environment

### PR DESCRIPTION
**Pull request by Norrox**
added an default color for preview environment and a button to change horizon color

image

### CODE REVIEW

**Review by sshiiden — APPROVED** [review]

**Review by Starkium — APPROVED** [review]

**Review by jss2a98aj — CHANGES_REQUESTED** [review]
Being able to set a horizion color is great. I do not think defaulting Sky, ground, and horizon colors all to the same color is good. Keeping purple for the horizon, but reverting sky and ground colors would look nicer and be a more developer friendly default.
Reverting the two suggested colors would look like this:
image

**Comment by Norrox** [comment]
Im all for having different colors, but please. No poop color on the ground 😂🙈

**Comment by Norrox** [comment]
I can suggest 
Greyish or more blue

Examples from unreal and unity 

image
![Uploading 377732962...]

**Comment by jss2a98aj** [comment]
Something like `0.333, 0.333, 0.333` could work for the ground then.

**Review by RandomOfNoWhere — APPROVED** [review]

**Comment by Norrox** [comment]
> Something like `0.333, 0.333, 0.333` could work for the ground then.

Yeah that can work! i'll change it!

**Comment by Norrox** [comment]
image

**Pull request merged**
