### PR TITLE
Make `EditorPlugin` emits `scene_changed` when replacing empty scenes.

### PR DESCRIPTION
**Pull request by WhalesState**

### CODE REVIEW

**Comment by jss2a98aj** [comment]
The test that failed here doesn't seem to have failed due to your changes. We should probably re-run it soon.

**Review by jss2a98aj — APPROVED** [review]
Re-running the previously failed test resulted in a pass. The changes here seem fine.

**Review by Starkium — DISMISSED** [review]

**Comment by salianifo** [comment]
*Note for context: Although this signal **doesn't** have the parameter, the one ultimately emitted on `EditorPlugin` **does** include the scene's root node of the currently edited scene at the **time the signal is emitted**.*

My only concern with this, is the other location this signal is emitted, `EditorNode::_set_main_scene_state`, is only called deferred. I didn't notice any problems in my testing, but it does cause a slight inconsistency when reloading the project.

Previously, when reloading the project with 2+ scenes being restored, this signal is emitted multiple times, but since it is deferred, it passes the scene that becomes active at the end for each signal.

With this change however, the first signal is emitted with the first loaded scene (since it is replacing an empty scene), and the rest with the scene that becomes active at the end.

In case that was confusing, here's a concrete example. We have 3 scenes open (Test1, Test2, and Test3). Test3 is currently active. We have a plugin that listens to this signal and prints the root node name. We reload the project and observe the following in the output:

- Previous results:
  - Test3
  - Test3
  - Test3

- New results:
  - Test1
  - Test3
  - Test3

Not sure it is a *real* problem, but it makes me wonder if there was a reason it was deferred in the first place. If there isn't a reason for it to be deferred, then we should consider making the signal not deferred in other places, or at least when loading scenes. Not sure how feasible that is though, the code for this is kind of all over the place, and I'm sure at least *some* of those places need it to be deferred to have everything set up correctly.

**Review by RandomOfNoWhere — APPROVED** [review]

**Comment by jss2a98aj** [comment]
> _Note for context: Although this signal **doesn't** have the parameter, the one ultimately emitted on `EditorPlugin` **does** include the scene's root node of the currently edited scene at the **time the signal is emitted**._

That is an interesting observation. It is possible that emitting it for each scene with the correct scene root, or queuing it so it is only emitted once with the most recent scene root would be correct behavior.

**Comment by WhalesState** [comment]
I have fixed this, by not calling the signal when restoring scenes, so now the other issue is not related to this fix.

```c++
	if (replacing_empty_scene && !restoring_scenes) {
		editor_data.notify_edited_scene_changed();
		emit_signal(SNAME("scene_changed"));
	}
```

When reloading the project with 2 opened scenes, and the first tab is active, it prints the first scene twice, and when reloading while the second tab is active, it prints the first scene then the second one, this won't cause issues in an editor plugin but we should only emit the signal once after reloading the project and restoring all the scenes, and this can be opened as a new issue.

**Review by salianifo — APPROVED** [review]
Yeah, this is probably fine for now. We can address the other points in another PR later.

**Review by Bioblaze — APPROVED** [review]

**Review by sshiiden — APPROVED** [review]

**Review by Norrox — APPROVED** [review]

**Pull request merged**
