### PR TITLE
Rebranding /editor

### PR DESCRIPTION
**Pull request by RandomOfNoWhere**
This PR is for the rebranding of the editor, one more step towards rebranding being completed.

### CODE REVIEW

**Comment by Tekisasu-JohnK** [comment]
I saw some references to Redot in [editor/project_converter_3_to_4.cpp](https://github.com/blazium-engine/blazium/pull/19/files#diff-31eab91917c346a9f4ff4c97fe88c5b4829713dc283475ab718a1c70ba3dd5a0)

**Comment by RandomOfNoWhere** [comment]
> I saw some references to Redot in [editor/project_converter_3_to_4.cpp](https://github.com/blazium-engine/blazium/pull/19/files#diff-31eab91917c346a9f4ff4c97fe88c5b4829713dc283475ab718a1c70ba3dd5a0)

Removed 2 refrences! Thank you!

**Comment by RandomOfNoWhere** [comment]
This PR will be cleaned and rebased, do not merge

**Comment by RandomOfNoWhere** [comment]
Closed, a new PR will be made after the following actions are taken:
-Do not change comments that are still related to core GoDot code
-Either do not change translation files, or manually verify each string

**Pull request closed without merging**
