### PR TITLE
updated splash

### PR DESCRIPTION
**Pull request by Norrox**
new
image

old
image

### CODE REVIEW

**Review by Starkium — APPROVED** [review]

**Comment by Starkium** [comment]
I think with the way it's outlined and the closeness of the gap, probably going to look pretty aliased.

**Comment by Norrox** [comment]
> I think with the way it's outlined and the closeness of the gap, probably going to look pretty aliased.

want me to change it to something like this? 
image

**Review by RandomOfNoWhere — APPROVED** [review]

**Comment by sshiiden** [comment]
I think it would be better to follow the brand kit by keeping the old logo outline, removing the outline from the text, and changing the text color to match the one used in [Blazium Logo & Wordmark B.png](https://github.com/blazium-engine/blazium-assets/blob/main/Blazium%20Engine%20-%20Brand%20Kit/Logo%20%26%20Wordmark%20(vertical)/PNG/Blazium%20Logo%20%26%20Wordmark%20B.png)

**Comment by Starkium** [comment]
Text doesn't seem right still, but if I had to choose between all of them, I'd take this one
image

**Comment by Norrox** [comment]
> Text doesn't seem right still, but if I had to choose between all of them, I'd take this one image

Sir, tell me your desire

**Comment by Norrox** [comment]
@Starkium 
image

**Comment by Norrox** [comment]
image

**Comment by Norrox** [comment]
Is the last one ok? think it looks alright ? :D

**Comment by sshiiden** [comment]
I prefer this one
image

**Comment by Starkium** [comment]
bottom text can't be too small, so I agree with @sshiiden. I do think some form outline would make it easier to read against other backgrounds.

**Comment by Norrox** [comment]
> bottom text can't be too small, so I agree with @sshiiden. I do think some form outline would make it easier to read against other backgrounds.

image

**Comment by Norrox** [comment]
image

**Comment by Norrox** [comment]
> bottom text can't be too small, so I agree with @sshiiden. I do think some form outline would make it easier to read against other backgrounds.

But i think this will always be black, its the spash logo when you launch the project manager or editor/game

**Comment by DeeJayLSP** [comment]
I personally think the icon would be much better without an outline:
blazium

**Comment by Captain-Wet-Beard** [comment]
> The concept of the logo being above the i is interesting

Yeah, I like how the logo as the dot makes the i look like a candle.

**Comment by Starkium** [comment]
we can try it without the outline, can always switch later if need be. 
I do like the concept of the logo being the flame on the i, though it feels disconnected with the font. 
Let's workshop that idea so more, but I think this version is fine.
image

**Comment by Norrox** [comment]
Alright!, Ready to merge after checks! @Starkium @Captain-Wet-Beard :)

**Review by sshiiden — APPROVED** [review]

**Review by Captain-Wet-Beard — APPROVED** [review]

**Review by Starkium — APPROVED** [review]

**Pull request merged**
