### PR TITLE
Replace default editor font with Inter and decrease default size to 13

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Inter is a slightly more pleasant font to read than Noto Sans, and has been adopted by many open-source projects like GNOME and Blender.

This only replaces the Latin/Greek/Cyrillic variant, which has the same characters, and should not interfere with other writing systems.

A font size of 13 is usually considered big enough for reading.

Comparison below:

### Project Manager
Before:
image
After:
image

### Editor
Before:
image

After:
image

### CODE REVIEW

**Review by sshiiden — APPROVED** [review]

**Review by Starkium — APPROVED** [review]
I can't tell the difference looking at it, but sure sounds good

**Review by RandomOfNoWhere — APPROVED** [review]

**Review by jss2a98aj — APPROVED** [review]
I don't see any issues with this from a technical perspective.

**Comment by DeeJayLSP** [comment]
Should have mentioned, but this is an actual proposal discussion in Godot: https://github.com/godotengine/godot-proposals/discussions/9012

The difference is that I didn't enable any opentype feature.

**Review by Bioblaze — APPROVED** [review]

**Comment by Bioblaze** [comment]
Where is the repo you got the font from?

**Comment by DeeJayLSP** [comment]
> Where is the repo you got the font from?

It was downloaded from the official site: https://rsms.me/inter/

It links to the release download in the repo (https://github.com/rsms/inter/), which is credited in both COPYRIGHT.txt and thirdparty/README.md

**Review by Norrox — APPROVED** [review]

**Pull request merged**
