### PR TITLE
Optimize GLES3 CanvasLight calculations and make it precise.

### PR DESCRIPTION
**Pull request by WhalesState**
https://github.com/user-attachments/assets/775435d7-23e4-4a9d-930b-b6f1be1966b9

### CODE REVIEW

**Comment by jss2a98aj** [comment]
Can you upload a project with that test scene? I would like to benchmark it.

**Comment by WhalesState** [comment]
I have edited the project to use the default physics engine, and freezed all the physics nodes after 0.5 seconds because godot 2d physics performance will affect the benchmark.

[test.zip](https://github.com/user-attachments/files/17964886/test.zip)

**Review by sshiiden — APPROVED** [review]

**Comment by jss2a98aj** [comment]
I am getting slightly worse performance in the test with the changes. I am going to try production builds next to see if it changes anything.

Before
```
Project FPS: 1216 (0.82 mspf)
Project FPS: 1249 (0.80 mspf)
Project FPS: 1250 (0.80 mspf)
Project FPS: 1244 (0.80 mspf)
Project FPS: 1215 (0.82 mspf)
Project FPS: 1210 (0.82 mspf)
Project FPS: 1238 (0.80 mspf)
```

After
```
Project FPS: 1178 (0.84 mspf)
Project FPS: 1178 (0.84 mspf)
Project FPS: 1170 (0.85 mspf)
Project FPS: 1169 (0.85 mspf)
Project FPS: 1179 (0.84 mspf)
Project FPS: 1156 (0.86 mspf)
Project FPS: 1145 (0.87 mspf)
```

**Comment by WhalesState** [comment]
> With `production=yes` performance is almost the same between the two implementations. Before

I see that after is faster by nearly 10 frames most of the time, also we are just skipping some useless calculactions that happens 4 times for each light update frame.

```c++
// Before
for (int i = 0; i < 4; i++) {
	Vector3 cam_target = Basis::from_euler(Vector3(0, 0, Math_TAU * ((i + 3) / 4.0))).xform(Vector3(0, 1, 0));
	projection = projection * Projection(Transform3D().looking_at(cam_target, Vector3(0, 0, -1)).affine_inverse());
}
```

```c++
// After
Projection projections[4] = {
	Projection(Vector4(0, 0, -1, 0), Vector4(1, 0, 0, 0), Vector4(0, -1, 0, 0), Vector4(0, 0, 0, 1)),
	Projection(Vector4(-1, 0, 0, 0), Vector4(0, 0, -1, 0), Vector4(0, -1, 0, 0), Vector4(0, 0, 0, 1)),
	Projection(Vector4(0, 0, 1, 0), Vector4(-1, 0, 0, 0), Vector4(0, -1, 0, 0), Vector4(0, 0, 0, 1)),
	Projection(Vector4(1, 0, 0, 0), Vector4(0, 0, 1, 0), Vector4(0, -1, 0, 0), Vector4(0, 0, 0, 1))
};
for (int i = 0; i < 4; i++) {
	projection = projection * projections[i];
}
```

**Comment by WhalesState** [comment]
I have done some more changes to make it slightly faster.
Building both locally with `optimize=none`.

// Before
Project FPS: 103 (9.70 mspf)
Project FPS: 102 (9.80 mspf)
Project FPS: 105 (9.52 mspf)
Project FPS: 104 (9.61 mspf)
Project FPS: 104 (9.61 mspf)
Project FPS: 104 (9.61 mspf)
Project FPS: 105 (9.52 mspf)
Project FPS: 108 (9.25 mspf)
Project FPS: 104 (9.61 mspf)
Project FPS: 108 (9.25 mspf)

// After
Project FPS: 113 (8.84 mspf)
Project FPS: 104 (9.61 mspf)
Project FPS: 104 (9.61 mspf)
Project FPS: 104 (9.61 mspf)
Project FPS: 108 (9.25 mspf)
Project FPS: 104 (9.61 mspf)
Project FPS: 110 (9.09 mspf)
Project FPS: 112 (8.92 mspf)
Project FPS: 105 (9.52 mspf)
Project FPS: 113 (8.84 mspf)

**Review by jss2a98aj — APPROVED** [review]
> I have done some more changes to make it slightly faster. Building both locally with `optimize=none`.

I tried it with `optimize=none` as well, and the performance improvement is cleanly past margin of error.
Before
```
Project FPS: 668 (1.49 mspf)
Project FPS: 670 (1.49 mspf)
Project FPS: 669 (1.49 mspf)
Project FPS: 670 (1.49 mspf)
Project FPS: 670 (1.49 mspf)
Project FPS: 664 (1.50 mspf)
Project FPS: 670 (1.49 mspf)
```
After
```
Project FPS: 684 (1.46 mspf)
Project FPS: 681 (1.46 mspf)
Project FPS: 681 (1.46 mspf)
Project FPS: 683 (1.46 mspf)
Project FPS: 685 (1.45 mspf)
Project FPS: 684 (1.46 mspf)
Project FPS: 684 (1.46 mspf)
```

`production=yes` still just barely performs better, though within margin of error. I think this will be most beneficial on older systems. Those do need performance improvements the most anyways.

**Review by Bioblaze — APPROVED** [review]

**Pull request merged**
